import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFile} from 'node:fs/promises';
async function load(relative){const source=await readFile(new URL(relative,import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));}
const {allowedEmail,sameOrigin}=await load('../lib/auth-policy.ts');
const {metaEvents,validMetaSignature}=await load('../lib/meta-protocol.ts');
test('workspace access fails closed and needs verified allowlisted email',()=>{assert.equal(allowedEmail('owner@test.example',true,''),false);assert.equal(allowedEmail('owner@test.example',false,'owner@test.example'),false);assert.equal(allowedEmail('attacker@test.example',true,'owner@test.example'),false);assert.equal(allowedEmail('OWNER@test.example',true,' owner@test.example '),true);});
test('writes require same-origin; foreign and missing Origin rejected',()=>{assert.equal(sameOrigin(new Request('https://crm.example/api',{headers:{Origin:'https://crm.example'}})),true);assert.equal(sameOrigin(new Request('https://crm.example/api',{headers:{Origin:'https://evil.example'}})),false);assert.equal(sameOrigin(new Request('https://crm.example/api')),false);});
test('Meta signature rejects modified payloads and invalid IDs',async()=>{const raw=JSON.stringify({object:'page',entry:[{id:'123',changes:[{field:'leadgen',value:{leadgen_id:'456'}}]}]});const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('test-secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature='sha256='+Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw))).toString('hex');assert.equal(await validMetaSignature(raw,signature,'test-secret'),true);assert.equal(await validMetaSignature(raw+' ',signature,'test-secret'),false);assert.equal(await validMetaSignature(raw,null,'test-secret'),false);assert.equal(metaEvents(JSON.parse(raw))[0].leadId,'456');assert.throws(()=>metaEvents({object:'page',entry:[{id:'123',changes:[{field:'leadgen',value:{leadgen_id:'../evil'}}]}]}));});

test('both configured production domains work behind an internal proxy',()=>{const old=process.env.CRM_ORIGIN;try{process.env.CRM_ORIGIN='https://cs.mustaction.my,https://maction-cs--maction-cs.asia-east1.hosted.app';for(const origin of process.env.CRM_ORIGIN.split(','))assert.equal(sameOrigin(new Request('http://internal/api',{headers:{Origin:origin}})),true);assert.equal(sameOrigin(new Request('http://internal/api',{headers:{Origin:'https://evil.example'}})),false);}finally{if(old===undefined)delete process.env.CRM_ORIGIN;else process.env.CRM_ORIGIN=old;}});
