'use client';
import {useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
import type {Course} from '@/lib/crm';
export default function WhatsAppConnection({courses}:{courses:Course[]}){
 const [info,setInfo]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 const [template,setTemplate]=useState('hello_world'),[language,setLanguage]=useState('en_US'),[parameters,setParameters]=useState(''),[image,setImage]=useState('');
 const [name,setName]=useState(''),[body,setBody]=useState(''),[draftLanguage,setDraftLanguage]=useState('zh_CN'),[category,setCategory]=useState('MARKETING'),[examples,setExamples]=useState(''),[file,setFile]=useState<File|null>(null),[courseId,setCourseId]=useState('');const requestId=useRef('');
 async function load(){try{const r=await fetch('/api/integrations/whatsapp');const b=await r.json();if(!r.ok)throw new Error(b.error||'无法读取 WhatsApp 设置');setInfo(b);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function action(payload:any){if(lock.current)return;lock.current=true;setBusy(true);try{const r=await fetch('/api/integrations/whatsapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||'操作失败');toast.success(payload.action==='send'?'Meta 已接收发送请求，请查看送达状态':payload.action==='template'?'模板已提交 Meta，等待审核':'已保存');await load();return b;}catch(e){toast.error((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 async function submitTemplate(){if(lock.current)return;lock.current=true;setBusy(true);try{let headerHandle='';if(file){const form=new FormData();form.set('image',file);const r=await fetch('/api/integrations/whatsapp/image',{method:'POST',body:form}),b=await r.json();if(!r.ok)throw new Error(b.error);headerHandle=b.handle;}const r=await fetch('/api/integrations/whatsapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'template',name,language:draftLanguage,category,body,examples:examples?examples.split('\n'):[],headerHandle})}),b=await r.json();if(!r.ok)throw new Error(b.error);toast.success('模板已提交 Meta，等待审核');await load();}catch(e){toast.error((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const field=(label:string,children:React.ReactNode)=><label className="field"><span>{label}</span>{children}</label>;
 return <><section className="panel padded"><div className="panel-toolbar"><h2>WhatsApp API</h2><Button variant="outline" disabled={busy} onClick={load}>刷新状态</Button></div><p>测试发送号码：<strong>{info?.sender||'加载中'}</strong> · 接收号码：<strong>{info?.recipient||'加载中'}</strong></p><div className="connection-note">测试模式：只向已验证的测试接收号码发送。手机号码共存接入仍待 Meta 高级权限审核；客户自动发送尚未开启。OpenAI 接待尚未连接。</div>{error&&<p role="alert">{error}</p>}{info?.templateError&&<p role="alert">{info.templateError}</p>}<p className="muted">接收消息与送达回调：本站 /api/integrations/meta，需在 Meta 的 WhatsApp 配置订阅 messages。服务器验证 Meta 签名后才保存。</p><Button variant="outline" disabled={busy||!info?.configured} onClick={()=>action({action:'subscribe'})}>订阅测试 WhatsApp 账户回调</Button></section>
 <div className="two-col"><section className="panel padded"><h2>发送测试模板</h2><p className="muted">仅管理员可发送。Meta 接收请求不等于客户已收到，实际送达以回调记录为准。</p>{field('已批准模板',<select className="pick" value={template+'|'+language} onChange={e=>{const [n,l]=e.target.value.split('|');setTemplate(n);setLanguage(l);requestId.current='';}}><option value="hello_world|en_US">hello_world · en_US</option>{info?.templates?.filter((t:any)=>t.status==='APPROVED'&&t.name!=='hello_world').map((t:any)=><option key={t.id} value={t.name+'|'+t.language}>{t.name} · {t.language}</option>)}</select>)}{field('正文变量（按顺序，每行一个；无变量留空）',<Textarea value={parameters} onChange={e=>{setParameters(e.target.value);requestId.current='';}} rows={3}/>)}{field('图片链接（仅图片头部模板填写，公开 HTTPS）',<Input type="url" value={image} onChange={e=>{setImage(e.target.value);requestId.current='';}}/>)}<Button disabled={busy||!info?.configured} onClick={()=>{requestId.current ||= crypto.randomUUID();void action({action:'send',requestId:requestId.current,to:info.recipient,template,language,parameters:parameters?parameters.split('\n'):[],image}).then(result=>{if(result)requestId.current='';});}}>发送一条到我的测试号码</Button><p className="footnote">失败或结果不明时，同一请求不会自动重复发送。核对记录后刷新页面可建立新的测试请求。</p></section>
 <section className="panel padded"><h2>创建文案／图片模板</h2>{field('模板名称（例如 maction_preview_welcome）',<Input value={name} onChange={e=>setName(e.target.value)} placeholder="小写英文及下划线"/>)}{field('语言',<select className="pick" value={draftLanguage} onChange={e=>setDraftLanguage(e.target.value)}><option value="zh_CN">简体中文</option><option value="en_US">English</option><option value="ms">Bahasa Melayu</option></select>)}{field('类别',<select className="pick" value={category} onChange={e=>setCategory(e.target.value)}><option value="MARKETING">Marketing · 课程介绍与邀请</option><option value="UTILITY">Utility · 已确认报名的事务通知</option></select>)}{field('正文',<Textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} placeholder="你好 {{1}}，感谢你咨询 {{2}}。"/>)}{field('变量示例（每行一个，请用虚构资料）',<Textarea rows={3} value={examples} onChange={e=>setExamples(e.target.value)} placeholder={'示例客户\n连锁课程'}/>)}{field('图片头部（可选，PNG／JPEG ≤ 5MB）',<Input type="file" accept="image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/>)}<Button disabled={busy||!info?.configured||!name||!body} onClick={submitTemplate}>提交 Meta 模板审核</Button><p className="footnote">提交的是当前正文、示例和图片；Meta 决定类别与审核结果。</p></section></div>
 <section className="panel padded"><h2>项目发送配置</h2><p>先保存每门课程对应的模板。当前配置保持停用，接入正式号码和客户联系同意后才能开启自动发送。</p>{field('课程',<select className="pick" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">选择课程</option>{courses.map(c=><option key={c.id} value={c.id}>{c.project} · {c.name}</option>)}</select>)}<p>使用上方测试发送区所选模板：{template} · {language}</p><Button disabled={busy||!courseId} onClick={()=>action({action:'route',courseId,template,language,image})}>保存项目模板（保持停用）</Button>{info?.routes?.map((r:any)=><p key={r.courseId}>{courses.find(c=>c.id===r.courseId)?.name||'课程'} · {r.template} · 未启用</p>)}</section>
 <section className="panel padded"><h2>模板审核状态</h2>{info?.templates?.length?<div className="table-scroll"><table><thead><tr><th>模板</th><th>语言</th><th>类别</th><th>状态</th></tr></thead><tbody>{info.templates.map((t:any)=><tr key={t.id}><td>{t.name}</td><td>{t.language}</td><td>{t.category}</td><td>{t.status}</td></tr>)}</tbody></table></div>:<p>暂无模板；可以刷新或提交新模板。</p>}</section>
 <section className="panel padded"><h2>WhatsApp 消息记录</h2><p className="muted">最近 50 条；入站文本和出站状态单独保存，不写入公开客户端数据库。</p>{info?.messages?.length?<div className="table-scroll"><table><thead><tr><th>时间（MYT）</th><th>方向／号码</th><th>模板／消息</th><th>状态</th></tr></thead><tbody>{info.messages.map((m:any)=><tr key={m.id}><td>{new Date(m.createdAt).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'})}</td><td>{m.direction==='inbound'?'收到':'发送'} · {m.to||m.from}</td><td style={{whiteSpace:'pre-wrap'}}>{m.template||m.text||m.type}{m.error&&<p>{m.error}</p>}</td><td>{({accepted:'Meta 已接收',sending:'发送中',sent:'已发送',delivered:'已送达',read:'已读',received:'已收到',failed:'失败',failed_or_unknown:'失败／结果待核对'} as Record<string,string>)[m.status]||m.status}</td></tr>)}</tbody></table></div>:<p>暂无系统消息记录。Meta 开发者页面的历史测试不会自动补入。</p>}</section></>;
}
