export const stages = ['New Lead','No Answer','No Answer > 3 times','Follow Up','Potential for Next Preview','Old Leads - Preview Incomplete','Old Leads - Preview Completed','Not Interested','Junk','Preview Scheduled','Preview Completed','Preview Attend < 30 Min','Preview Absent','Close Won','Lost / Not Interested after Preview'];
export type Course={id:string;name:string;project:string;description:string;price:number;teamIds:string[];assignment:string;aiInstructions:string};
export type Session={id:string;courseId:string;name:string;startsAt:string;intakeUntil:string;teacher:string;mode:string;location:string;accepting:boolean};
export type Member={id:string;name:string;role:string;active:boolean};
export type Activity={id:string;at:string;actor:string;type:string;text:string;sessionId:string|null};
export type Lead={id:string;name:string;phone:string;company:string;courseId:string;sessionId:string|null;ownerId:string|null;stage:string;account:string;page:string;campaign:string;ad:string;form:string;createdAt:string;nextFollowUp:string;optedIn:boolean;aiPaused:boolean;revenue:number;activities:Activity[];externalId:string;metaLeadIds?:string[]};
export type SourceRule={id:string;name:string;account:string;page:string;form:string;courseId:string;sessionId:string|null};
export type Spend={id:string;date:string;courseId:string;sessionId:string|null;account:string;page:string;campaign:string;amount:number;metaLeads:number};
export type CRM={courses:Course[];sessions:Session[];members:Member[];leads:Lead[];rules:SourceRule[];spend:Spend[];settings:{greeting:string;reminderHours:number;aiEnabled:boolean};demo:boolean;counters:Record<string,number>};
export const uid=()=>crypto.randomUUID();export const now=()=>new Date().toISOString();
export function initialState():CRM{return{courses:[],sessions:[],members:[],leads:[],rules:[],spend:[],settings:{greeting:'你好 {{name}}，我们收到你对 {{course}} 的咨询。下一场 Preview：{{date}}，地点：{{location}}。请问方便参加吗？',reminderHours:24,aiEnabled:false},demo:false,counters:{}};}
export function sessionFor(s:CRM,courseId:string,at=now()){return s.sessions.filter(e=>e.courseId===courseId&&e.accepting&&new Date(e.startsAt)>new Date(at)&&new Date(e.intakeUntil)>new Date(at)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0]||null;}
export function ownerFor(s:CRM,c:Course){const ids=c.teamIds.filter(id=>s.members.some(m=>m.id===id&&m.active));if(!ids.length)return null;const n=s.counters[c.id]||0;s.counters[c.id]=n+1;return ids[c.assignment==='fixed'?0:n%ids.length];}
export function activity(l:Lead,type:string,text:string,actor:string){l.activities.push({id:uid(),at:now(),actor,type,text,sessionId:l.sessionId});}
export function sampleState():CRM{const s=initialState();s.demo=true;s.members=[{id:'m1',name:'Amanda（示例）',role:'课程顾问',active:true},{id:'m2',name:'Wilson（示例）',role:'课程顾问',active:true}];s.courses=[{id:'c1',name:'Franchise A-Z',project:'连锁',description:'连锁经营课程 Preview。',price:388,teamIds:['m1','m2'],assignment:'round-robin',aiInstructions:'先了解经营背景，再邀请参加 Preview。'},{id:'c2',name:'绩效管理',project:'品誉',description:'绩效管理课程 Preview。',price:980,teamIds:['m1'],assignment:'fixed',aiInstructions:'无法确认的问题转真人。'}];const day=(n:number,h=20)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+n);d.setUTCHours(h-8,0,0,0);return d.toISOString();};s.sessions=[{id:'e0',courseId:'c1',name:'Franchise A-Z · 上一场',startsAt:day(-2),intakeUntil:day(-2),teacher:'Jacky（示例）',mode:'线上',location:'Zoom',accepting:false},{id:'e1',courseId:'c1',name:'Franchise A-Z · 下一场线上 Preview',startsAt:day(7),intakeUntil:day(7),teacher:'Jacky（示例）',mode:'线上',location:'Zoom · 链接待填写',accepting:true},{id:'e2',courseId:'c1',name:'Franchise A-Z · JB 实体 Preview',startsAt:day(14,14),intakeUntil:day(14,12),teacher:'Jacky（示例）',mode:'线下',location:'JB · 场地待填写',accepting:true},{id:'e3',courseId:'c2',name:'绩效管理 · 线上 Preview',startsAt:day(9),intakeUntil:day(9),teacher:'李老师（示例）',mode:'线上',location:'Zoom',accepting:true}];s.leads=['陈志明','林美琪','黄家伟','张慧欣','李文杰','周丽萍','吴俊豪','许雅婷'].map((name,i)=>{const c=s.courses[i%3===0?1:0],e=sessionFor(s,c.id)!;return{id:'l'+i,name:name+'（示例）',phone:'',company:['餐饮企业','零售门市','教育机构','美容中心'][i%4],courseId:c.id,sessionId:e.id,ownerId:i===7?null:i%2?'m1':'m2',stage:['New Lead','Follow Up','No Answer','Preview Scheduled','Preview Completed','Preview Absent','Close Won','Follow Up'][i],account:i%2?'示例广告户口 A':'示例广告户口 B',page:i%2?'示例连锁 Page':'示例课程 Page',campaign:'Preview 招生（示例）',ad:'示例广告',form:'示例表单',createdAt:day(-i-1,10),nextFollowUp:day(i%3===0?-1:1,10),optedIn:false,aiPaused:true,revenue:i===6?388:0,externalId:'',activities:[{id:uid(),at:day(-i-1,10),actor:'系统',type:'lead',text:'示例 Lead 自动分配课程与场次。',sessionId:e.id},...(i>0?[{id:uid(),at:day(-1,11),actor:'Amanda（示例）',type:'note',text:'客户想了解课程内容，约好下一次联系。',sessionId:e.id}]:[])]};});s.leads[5].activities.splice(1,0,{id:uid(),at:day(-1,9),actor:'Wilson（示例）',type:'transfer',text:'从「上一场」转至「下一场线上 Preview」；原因：客户时间不合。',sessionId:'e1'});s.rules=[{id:'r1',name:'连锁课程表单',account:'',page:'示例连锁 Page',form:'示例表单',courseId:'c1',sessionId:null}];s.spend=[{id:'s1',date:new Date().toISOString().slice(0,10),courseId:'c1',sessionId:'e1',account:'示例广告户口 A',page:'示例连锁 Page',campaign:'Preview 招生（示例）',amount:1250,metaLeads:32},{id:'s2',date:new Date().toISOString().slice(0,10),courseId:'c2',sessionId:'e3',account:'示例广告户口 B',page:'示例课程 Page',campaign:'Preview 招生（示例）',amount:780,metaLeads:18}];return s;}
