'use client';
import {useState} from 'react';
import {initializeApp,getApps} from 'firebase/app';
import {getAuth,signInWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,setPersistence,inMemoryPersistence,signOut,type Auth} from 'firebase/auth';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function Login(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function authClient(){const r=await fetch('/api/auth/config');const p=await r.json();if(!r.ok)throw new Error('登录服务暂时不可用，请稍后重试');const auth=getAuth(getApps()[0]||initializeApp(p));await setPersistence(auth,inMemoryPersistence);return auth;}
 async function login(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');let auth:Auth|undefined;try{
  auth=await authClient();const result=await signInWithEmailAndPassword(auth,email.trim(),password);
  if(!result.user.emailVerified){await sendEmailVerification(result.user,{url:window.location.origin+'/login'});setNotice('验证邮件已发送到你的邮箱。请打开邮件完成验证，然后回来登录；也请检查垃圾邮件。');return;}
  const r=await fetch('/api/auth/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:await result.user.getIdToken(true)})});if(!r.ok){let p:any={};try{p=await r.json();}catch{}throw new Error(p.error||'登录失败，请重试');}window.location.assign('/');
 }catch(e){const code=(e as {code?:string}).code;setError(code==='auth/invalid-credential'||code==='auth/wrong-password'||code==='auth/user-not-found'?'邮箱或密码不正确':code==='auth/too-many-requests'?'操作过于频繁，请稍后重试':code==='auth/operation-not-allowed'?'邮箱密码登录尚未启用，请联系管理员':code==='auth/network-request-failed'?'网络连接失败，请重试':code==='auth/user-disabled'?'此账号已停用，请联系管理员':code?'登录失败，请检查邮箱和密码后重试':(e as Error).message);}finally{if(auth)await signOut(auth).catch(()=>{});setPassword('');setBusy(false);}}
 async function reset(){if(busy)return;if(!email.trim()){setError('请先填写登录邮箱');return;}setBusy(true);setError('');setNotice('');let auth:Auth|undefined;try{auth=await authClient();await sendPasswordResetEmail(auth,email.trim(),{url:window.location.origin+'/login'});setNotice('如果该邮箱已注册，你会收到密码重设邮件。请自行在邮件链接中设置密码。');}catch{setError('暂时无法发送重设邮件，请稍后重试');}finally{if(auth)await signOut(auth).catch(()=>{});setBusy(false);}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#f7f5f5'}}><section className="panel padded" style={{maxWidth:440,width:'100%'}}><div className="brand" style={{padding:'0 0 25px',color:'#7f1d1d'}}><div className="brand-mark" style={{background:'#c62828'}}>M</div><div><strong>MACTION</strong><small style={{color:'#7f1d1d'}}>客服中心</small></div></div><h1 style={{fontSize:26,fontWeight:700}}>登录客户工作区</h1><p className="muted">使用获授权的邮箱及密码，管理课程、Preview 与客户跟进。</p><form onSubmit={login}><label className="field"><span>邮箱</span><Input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy} placeholder="你的登录邮箱"/></label><label className="field"><span>密码</span><Input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><Button type="submit" disabled={busy} style={{width:'100%'}}>{busy?'正在处理…':'使用邮箱密码登录'}</Button><Button type="button" variant="ghost" disabled={busy} onClick={reset} style={{width:'100%',marginTop:8}}>忘记密码</Button></form>{error&&<p role="alert" style={{color:'#c62828',marginTop:20}}>{error}</p>}{notice&&<p role="status" style={{marginTop:20}}>{notice}</p>}<p className="footnote">仅向获授权且已验证邮箱的账号开放。团队成员由总管理员在系统内分配项目。</p></section></main>;
}
