import {getUser} from '@/app/firebase-auth';
import {sameOrigin} from '@/lib/auth-policy';
import { readState,saveState } from '@/lib/store';
import { activity,initialState,sampleState,sessionFor,ownerFor,stages,uid,now, Lead } from '@/lib/crm';
export async function GET(){try{if(!await getUser())return Response.json({error:'请先登录'},{status:401});return Response.json(await readState());}catch(e){console.error(e);return Response.json({error:'资料加载失败，请稍后重试。'},{status:503});}}
const str=(v:unknown)=>typeof v==='string'?v.trim():'';
export async function POST(req:Request){try{const user=await getUser();if(!user)return Response.json({error:'请先登录'},{status:401});if(!sameOrigin(req))return Response.json({error:'不允许此请求'},{status:403});const b=await req.json() as any; if(!b || typeof b.action!=='string') return Response.json({error:'无效请求'},{status:400});const {state:s,revision}=await readState();if(b.revision!==revision)return Response.json({error:'资料已更新，请刷新后再试。'},{status:409});const p=b.payload||{},actor=user.displayName;let next=s;
 if(b.action==='demo'){if(s.leads.length||s.courses.length)throw new Error('已有资料，不能载入示例。');next=sampleState();}
 else if(b.action==='clearDemo'){if(!s.demo)throw new Error('仅能清除示例工作区');next=initialState();}
 else if(b.action==='course'){if(!str(p.name)||!str(p.project))throw new Error('请填写课程名字及项目');if(!Array.isArray(p.teamIds)||p.teamIds.some((id:string)=>!s.members.some(m=>m.id===id)))throw new Error('人员不存在');const obj={id:p.id||uid(),name:str(p.name),project:str(p.project),description:str(p.description),price:Math.max(0,Number(p.price)||0),teamIds:p.teamIds,assignment:p.assignment==='fixed'?'fixed':'round-robin',aiInstructions:str(p.aiInstructions)};const i=s.courses.findIndex(c=>c.id===p.id);if(i>=0)s.courses[i]=obj;else s.courses.push(obj);}
 else if(b.action==='member'){if(!str(p.name))throw new Error('请填写人员名字');const obj={id:p.id||uid(),name:str(p.name),role:str(p.role)||'课程顾问',active:p.active!==false};const i=s.members.findIndex(m=>m.id===p.id);if(i>=0)s.members[i]=obj;else s.members.push(obj);}
 else if(b.action==='session'){if(!s.courses.some(c=>c.id===p.courseId)||!str(p.name)||!str(p.teacher)||!str(p.location))throw new Error('请填写课程、名字、老师和地点');if(!Number.isFinite(Date.parse(p.startsAt))||!Number.isFinite(Date.parse(p.intakeUntil))||Date.parse(p.intakeUntil)>Date.parse(p.startsAt))throw new Error('接收截止时间必须不晚于开场时间');const obj={id:p.id||uid(),courseId:p.courseId,name:str(p.name),startsAt:new Date(p.startsAt).toISOString(),intakeUntil:new Date(p.intakeUntil).toISOString(),teacher:str(p.teacher),mode:p.mode==='线下'?'线下':'线上',location:str(p.location),accepting:!!p.accepting};const i=s.sessions.findIndex(e=>e.id===p.id);if(i>=0){if(s.sessions[i].courseId!==obj.courseId&&s.leads.some(l=>l.sessionId===obj.id))throw new Error('已有客户的场次不能更换课程');s.sessions[i]=obj;}else s.sessions.push(obj);}
 else if(b.action==='lead'){const c=s.courses.find(c=>c.id===p.courseId);if(!c||!str(p.name))throw new Error('请填写客户名字和课程');const phone=str(p.phone).replace(/[\s()-]/g,'');if(phone&&!/^\+?\d{8,15}$/.test(phone))throw new Error('请填写包含国家代码的有效电话号码');if(phone&&s.leads.some(l=>l.phone===phone))throw new Error('此电话号码已有客户，请打开原客户记录跟进或转场');let e=p.sessionId?s.sessions.find(e=>e.id===p.sessionId&&e.courseId===c.id):sessionFor(s,c.id);if(p.sessionId&&!e)throw new Error('场次不属于该课程');const l:Lead={id:uid(),name:str(p.name),phone,company:str(p.company),courseId:c.id,sessionId:e?.id||null,ownerId:ownerFor(s,c),stage:'New Lead',account:str(p.account),page:str(p.page),campaign:str(p.campaign),ad:str(p.ad),form:str(p.form),createdAt:now(),nextFollowUp:'',optedIn:!!p.optedIn,aiPaused:true,revenue:0,externalId:'',activities:[]};activity(l,'lead',`新增客户；分配至「${e?.name||'待分配场次'}」；负责人：${s.members.find(m=>m.id===l.ownerId)?.name||'待分配'}`,actor);s.leads.unshift(l);}
 else if(['note','stage','transfer','owner','followUp','aiPause','revenue'].includes(b.action)){const l=s.leads.find(l=>l.id===p.id);if(!l)throw new Error('找不到客户');if(b.action==='note'){if(!str(p.text)||!Number.isFinite(Date.parse(p.at)))throw new Error('请填写联系时间和记录');l.activities.push({id:uid(),at:new Date(p.at).toISOString(),actor,type:'note',text:`${str(p.channel)||'联系'}：${str(p.text)}`,sessionId:l.sessionId});if(p.nextFollowUp)l.nextFollowUp=new Date(p.nextFollowUp).toISOString();}
 if(b.action==='stage'){if(!stages.includes(p.stage))throw new Error('无效阶段');activity(l,'stage',`${l.stage} → ${p.stage}`,actor);l.stage=p.stage;}
 if(b.action==='transfer'){const e=s.sessions.find(e=>e.id===p.sessionId&&e.courseId===l.courseId);if(!e||e.id===l.sessionId||!str(p.reason))throw new Error('请选择同课程的其他场次，并填写原因');const from=s.sessions.find(e=>e.id===l.sessionId);const previous=l.stage;l.sessionId=e.id;l.stage='Follow Up';activity(l,'transfer',`从「${from?.name||'待分配'}」转至「${e.name}」；原因：${str(p.reason)}；Stage：${previous} → Follow Up`,actor);}
 if(b.action==='owner'){if(p.ownerId&&!s.members.some(m=>m.id===p.ownerId&&m.active))throw new Error('人员不可用');activity(l,'owner',`负责人：${s.members.find(m=>m.id===l.ownerId)?.name||'未分配'} → ${s.members.find(m=>m.id===p.ownerId)?.name||'未分配'}`,actor);l.ownerId=p.ownerId||null;}
 if(b.action==='followUp'){l.nextFollowUp=p.at?new Date(p.at).toISOString():'';activity(l,'task',`下次跟进：${l.nextFollowUp||'已清除'}`,actor);}
 if(b.action==='aiPause'){l.aiPaused=!!p.paused;activity(l,'ai',l.aiPaused?'真人接管，AI 已暂停':'允许 AI 接待（接通服务后生效）',actor);}
 if(b.action==='revenue'){const amount=Number(p.amount);if(!Number.isFinite(amount)||amount<0)throw new Error('金额无效');l.revenue=amount;activity(l,'payment',`记录实收金额 RM ${amount.toFixed(2)}`,actor);}}
 else if(b.action==='rule'){if(!s.courses.some(c=>c.id===p.courseId)||!str(p.name)||![p.account,p.page,p.form].some(str))throw new Error('请填写规则名称、课程和至少一个来源条件');if(p.sessionId&&!s.sessions.some(e=>e.id===p.sessionId&&e.courseId===p.courseId))throw new Error('指定场次不属于课程');const obj={id:p.id||uid(),name:str(p.name),account:str(p.account),page:str(p.page),form:str(p.form),courseId:p.courseId,sessionId:p.sessionId||null};const i=s.rules.findIndex(r=>r.id===p.id);if(p.id&&i<0)throw new Error('来源规则不存在');if(i>=0)s.rules[i]=obj;else s.rules.push(obj);}
 else if(b.action==='spend'){if(!s.courses.some(c=>c.id===p.courseId)||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||!str(p.account))throw new Error('请填写课程、日期和广告户口');const amount=Number(p.amount),count=Number(p.metaLeads);if(!Number.isFinite(amount)||amount<0||!Number.isInteger(count)||count<0)throw new Error('请填写有效消费及 Lead 数');if(p.sessionId&&!s.sessions.some(e=>e.id===p.sessionId&&e.courseId===p.courseId))throw new Error('场次不属于课程');s.spend.push({id:uid(),date:p.date,courseId:p.courseId,sessionId:p.sessionId||null,account:str(p.account),page:str(p.page),campaign:str(p.campaign),amount,metaLeads:count});}
 else if(b.action==='settings'){s.settings.greeting=str(p.greeting);s.settings.reminderHours=Math.max(1,Math.min(168,Number(p.reminderHours)||24));s.settings.aiEnabled=!!p.aiEnabled;}
 else throw new Error('不支持的操作');const rev=await saveState(next,revision);return Response.json({state:next,revision:rev});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'保存失败'},{status:400});}}

